In [40]:
#Domiciano Silveira Ribeiro
#RA: 12122CCP004
#Exerc.: 1

from google.colab import drive
drive.mount('/content/gdrive')
root_path = '/content/gdrive/My Drive/Colab Notebooks/RedesComp/'

import numpy as np

#Cada aluno cria a própria rede no padrão. :
#Criar um arquivo no formato texto com os dados da rede no padrão
#NóOrigem NóDestino
grafoimportado = np.loadtxt(root_path + "arq1.txt", np.integer)
print("Importação:", "\n", grafoimportado)

grafo = np.zeros((5, 7))
for x in grafoimportado:
  linha = x
  origem = 0
  destino = 0
  for y in linha:
    if (origem == 0):
      origem = y
    else:
      destino = y
    if (origem != 0 and destino != 0):
      grafo[origem - 1, destino - 1] = 1

#-> Montar a matriz de adjacência 
print("\n", "Matriz: ", "\n", grafo, "\n")

#-> Calcular o grau de cada nó 
#axis = 1 para calcular linha e axis = 0 para calcular coluna
grauvertice = np.sum(grafo, axis=1)
print("Grau: ", grauvertice, "\n")

#-> Calcular o grau médio 
print("Grau médio: ", np.mean(grafo))



Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Importação: 
 [[1 2]
 [2 3]
 [2 4]
 [5 6]
 [1 7]]

 Matriz:  
 [[0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]] 

Grau:  [2. 2. 0. 0. 1.] 

Grau médio:  0.14285714285714285
